Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Adonias 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/08/2019
Var
// Seção de Declarações das variáveis 
numero,res: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("insira um numero: ")
 leia(numero)
 res <- numero * 2
 escreval ("o dobro de", numero, " é:",res)

Fimalgoritmo